server:
  port: 50000

spring:
  application:
    name: yang-openfegin

#注册地址
eureka:
  client:
    service-url:
      defaultZone : http://${HOSTNAME:localhost}:${PORT:8888}/eureka

  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true

#logging
logging:
    level:
      root: debug

#
feign:
  client:
    config:
        logger.level: INFO
        connect.timeout: 1000





