server:
  port: 20000

spring:
  application:
    name: hello-server

eureka:
  client:
    service-url:
      defaultZone : http://${HOSTNAME:localhost}:${PORT:8888}/eureka

  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true



