server:
  port: 9999

spring:
  application:
    name: zuul-yang

####################################################################
zuul:
  #所有路由的公共前缀。
  prefix: /
  #忽略的服务ID列表，即使服务注册中心有这些服务，Zuul也不会路由到它们
  ignored-services: "*"

  # 是否添加Host头到请求中。
  add-host-header: true

  #敏感头信息，这些头信息在路由过程中不会被修改
  sensitive-headers: Cookie,Set-Cookie

  #是否开启重试机制
  retryable: true

  ## 定义路由规则，每个路由规则映射到一个服务
  routes:
    #自定义路由名称
     hello:
         # 路由路径，客户端通过这个路径访问服务
         path: /hello
         #路由到的服务实例的名称
         url: http://${HELLO_HOSTNAME:localhost}:${HELLO_PORT:20000}

     order-api:
       path: /order/**
       url: http://${HELLO_HOSTNAME:localhost}:${HELLO_PORT:20000}

     stock:
       path: /stock/**
       url: http://${HELLO_HOSTNAME:localhost}:${HELLO_PORT:20000}

     rest-api:
       path: /rest-api/**
       url: http://${REST_HOSTNAME:localhost}:${REST_PORT:8031}

     openFeign-api:
       path: /openFeign-api/**
       url: http://${FEIGN_HOSTNAME:localhost}:${FEIGN_PORT:50000}


####################################################################
logging:
  level:
    root: info


#熔断降级
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 # 命令执行的超时时间

      #circuitBreaker:
        #enabled: true # 是否启用熔断器
        #requestVolumeThreshold: 2 # 触发熔断的最小请求数
        #sleepWindowInMilliseconds: 5000 # 熔断器半开状态的检查间隔
        #errorThresholdPercentage: 50 # 触发熔断的错误百分比

#负载均衡
# ZoneAwareLoadBalancer



#ribbon:
  #ConnectTimeout: 3000 # 连接超时时间
  #ReadTimeout: 6000 # 读取超时时间
  #OkToRetryOnAllOperations: true # 是否对所有操作都重试
  #MaxAutoRetries: 1 # 当前实例的重试次数
  #MaxAutoRetriesNextServer: 1 # 切换实例的重试次数
  #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedRandomRule # 负载均衡算法，比如这里使用的是加权随机

# 针对特定服务的配置
#your-service-name:
  #ribbon:
    #listOfServers: localhost:8080 # 服务实例列表，通常通过服务发现自动填充

