server:
  port: 8031

spring:
  application:
    name: yang-rest


    loadbalancer:
      ribbon:
        enabled: false

#负载均衡


#熔断
hystrix:
  command:
    default:
        circuitBreaker:
           enabled: true # 是否启用熔断器
           requestVolumeThreshold: 2 # 触发熔断的最小请求数
           sleepWindowInMilliseconds: 5000 # 熔断器半开状态的检查间隔
           errorThresholdPercentage: 50 # 触发熔断的错误百分比

#注册地址
eureka:
  client:
    service-url:
      defaultZone : http://${HOSTNAME:localhost}:${PORT:8888}/eureka
